### PR TITLE
Encounter Extractor and Context Util Function

### PR DESCRIPTION
**Pull request by jafeltra**
# Summary
This adds a util function for getting Encounters from context. It also adds a simple FHIREncounterExtractor.

## New behavior
This repo doesn't use the context util function yet, so there are no new behavior changes related to that portion of this PR.

A new extractor was added for FHIR Encounters, because we will now need to extract these separately since we require them to be in context for other extractors in the Epic-MEF.

## Code changes
- Adds the util function and tests it
- Adds the extractor and tests it
- Also registers the new extractor in the MCODEClient

# Testing guidance
There will be instructions in the Epic-MEF to test the new util function, but ensure the tests here cover the functionality. Ensure that you can use the new extractor, but that will also need to be tested in the Epic-MEF branch.

Note that there will likely be merge conflict to resolve since I added code in the same places as #82, but I can resolve those once that gets in.

### CODE REVIEW

**Review by julianxcarter — APPROVED** [review]
Looks good to me!

**Review by kjmahalingam — APPROVED** [review]
Nice!

**Comment by Dtphelan1** [comment]
Is this good to merge? @jafeltra

**Comment by Dtphelan1** [comment]
LGTM

**Pull request merged**
