### PR TITLE
Remove EJS

### PR DESCRIPTION
**Pull request by kjmahalingam**
# Summary
Remove all lingering references to EJS and reformat template import/export structure.
## New behavior
None.
# Testing guidance
Run the tests and lint, and run it with the base client!

### CODE REVIEW

**Review by jafeltra — COMMENTED** [review]
This looks good! I think we should be able to remove the `ejs` dependency in package.json as well!

**Comment by kjmahalingam** [comment]
@jafeltra You're right! I removed it in the last commit.

**Review by jafeltra — APPROVED** [review]
This looks entirely excellent. See ya later EJS 👋

**Review by Dtphelan1 — APPROVED** [review]
looks great - fantastic work Dylan!

**Pull request merged**
