### PR TITLE
Updated README to include client usage instructions.

### PR DESCRIPTION
**Pull request by danlee1025**
# Summary
Updated README to include instructions on how to run client.
# Testing guidance
No code changes, ensure the instructions make sense and don't include any ICARE specific instructions.

### CODE REVIEW

**Comment by Dtphelan1** [comment]
DP1 - Definitely my fault from a previous PR, but since you're updating the TOC could you add a License section?

**Comment by danlee1025** [comment]
For DP1, do you mean somewhere else? I see it as a section in the table of contents.

**Comment by Dtphelan1** [comment]
lol nvm I'm blind.

**Review by Dtphelan1 — APPROVED** [review]
lgtm

**Review by jafeltra — APPROVED** [review]
This looks good to me!

**Pull request merged**
